[versions]
agp = "8.9.2"
kotlin = "2.0.21"
appcompat = "1.7.0"
material = "1.12.0"
cardview = "1.0.0"
constraintlayout = "2.1.4"
libxposedApi = "102.0.0"
libxposedService = "102.0.0"

[libraries]
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-cardview = { group = "androidx.cardview", name = "cardview", version.ref = "cardview" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
libxposed-api = { group = "io.github.libxposed", name = "api", version.ref = "libxposedApi" }
libxposed-service = { group = "io.github.libxposed", name = "service", version.ref = "libxposedService" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
